-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.dim_canal
(
    tipo_venta text COLLATE pg_catalog."default",
    tipo_cliente text COLLATE pg_catalog."default",
    id_canal bigint NOT NULL,
    CONSTRAINT dim_canal_pkey PRIMARY KEY (id_canal)
);

CREATE TABLE IF NOT EXISTS public.dim_geografia
(
    ciudad text COLLATE pg_catalog."default",
    pais text COLLATE pg_catalog."default",
    id_geografia bigint NOT NULL,
    CONSTRAINT dim_geografia_pkey PRIMARY KEY (id_geografia)
);

CREATE TABLE IF NOT EXISTS public.dim_producto
(
    producto text COLLATE pg_catalog."default",
    tipo_producto text COLLATE pg_catalog."default",
    id_producto bigint NOT NULL,
    CONSTRAINT dim_producto_pkey PRIMARY KEY (id_producto)
);

CREATE TABLE IF NOT EXISTS public.fact_ventas
(
    fecha timestamp without time zone,
    id_producto bigint,
    id_geografia bigint,
    id_canal bigint,
    cantidad double precision,
    precio_unitario double precision,
    descuento double precision,
    costo_envio double precision,
    total_ventas double precision
);

ALTER TABLE IF EXISTS public.fact_ventas
    ADD CONSTRAINT fk_canal FOREIGN KEY (id_canal)
    REFERENCES public.dim_canal (id_canal) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_ventas
    ADD CONSTRAINT fk_geografia FOREIGN KEY (id_geografia)
    REFERENCES public.dim_geografia (id_geografia) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_ventas
    ADD CONSTRAINT fk_producto FOREIGN KEY (id_producto)
    REFERENCES public.dim_producto (id_producto) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;